// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vputfpbhmrethjeqzsgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwdXRmcGJobXJldGhqZXF6c2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NTYxNjYsImV4cCI6MjA1MDUzMjE2Nn0.WOSTbk3M3DwChtrNRiPA07ZTttpq806oLatDGQuVLJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);